DROP TABLE IF EXISTS TRAIN_INFO;
CREATE TABLE TRAIN_INFO(TRAIN_NO INT PRIMARY KEY, TRAIN_NAME VARCHAR(255), DESC VARCHAR(255), START_POINT VARCHAR(255), END_POINT VARCHAR(255), TOTAL_CAPACITY INT, TOTAL_DISTANCE INT);
INSERT INTO TRAIN_INFO (TRAIN_NO, TRAIN_NAME, DESC, START_POINT, END_POINT, TOTAL_CAPACITY, TOTAL_DISTANCE) VALUES(1000, 'MS_MAQ', 'MANGALORE EXPRESS', 'CHENNAI', 'MANGALORE', 10, 500);
INSERT INTO TRAIN_INFO (TRAIN_NO, TRAIN_NAME, DESC, START_POINT, END_POINT, TOTAL_CAPACITY, TOTAL_DISTANCE) VALUES(1001, 'ROCKFORT_EXPRESS', 'ROCKFORT EXPRESS', 'TRICHY', 'CHENNAI', 10, 350);